spring:
  datasource:
    url: jdbc:postgresql://${db.server:localhost}:${db.port:54320}/ct
    username: tester
    password: dummy

  flyway:
    enabled: false

  output:
    ansi:
      enabled: always