spring:
  datasource:
    url: jdbc:postgresql://${db.server:localhost}:${db.port:54320}/ct
    username: tester
    password: dummy

  flyway:
    enabled: false
    default-schema: app

  http:
    client:
      factory: http-components
      connect-timeout: 3s
      read-timeout: 10s

  output:
    ansi:
      enabled: always

app:
  user:
    base-url: http://localhost:8088
